name: Create Cavatica Projects

on:
  issues:
    types:
      - opened

jobs:
  create_cavatica_project:
    runs-on: ubuntu-latest
    environment: cavatica-prod
    strategy:
      matrix:
        python-version: ['3.12.9']
    if: contains(github.event.issue.title, '[Project Creation]')

    steps:
      - name: Checkout API Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          token: ${{ secrets.MY_REPO_PAT }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ matrix.python-version }}
      - name: Debug workspace
        run: |
          pwd
          ls -R
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Project Creation Script
        run: |
          python scripts/create_project.py \
          --token ${{ secrets.CAVATICA_TOKEN }} \
          --body github.event.issue.body \
          --description github.event.issue.body \
          --run 
